### ISSUE TITLE
Discuss improvements and problems of current permission model

### ISSUE THREAD

**Issue by maierthomas** [eclipse-sw360/sw360#178]
<a href="https://github.com/bs-jokri"><img src="https://avatars2.githubusercontent.com/u/13886571?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bs-jokri](https://github.com/bs-jokri)**
_Monday Oct 09, 2017 at 10:59 GMT_
_Originally opened as https://github.com/sw360/sw360portal/issues/642_

----

_From @maxhbr on December 15, 2016 10:32_

_Copied from original issue: bsinno/sw360#376_

**Comment by mcjaeger** [comment]
also I do agree to the given points:

- [ ] a user, which is moved to another organization, should no longer be able to see his created projects
- [ ] admin should be able to see everything

- [ ] one should be able to change the owner of an project (maybe bulk)
- [ ] one should be able to change the organization of an project (maybe bulk)
- [ ] one should be able to be in multiple organizations
- [x] one should have a hierarchy of organizations (via liferay parent organizations)
- [ ] different roles in different organizations

not so logical maybe: 

`{clearing,...}_admin should have only permissions within his project` because in reality it is useful to have the super users around which can be contacted to correct things.

**Comment by mcjaeger** [comment]
multi group is going to happen here: https://github.com/eclipse/sw360/issues/1163
