### ISSUE TITLE
Build failure due to JDK 11.0.20

### ISSUE THREAD

**Issue by ag4ums** [eclipse-sw360/sw360#2086]
[//]: # (Copyright Siemens AG, 2021. Part of the SW360 Portal Project)
[//]: # (This program and the accompanying materials are made)
[//]: # (available under the terms of the Eclipse Public License 2.0)
[//]: # (which is available at https://www.eclipse.org/legal/epl-2.0/)
[//]: # (SPDX-License-Identifier: EPL-2.0)

### Description

Sw360 builds are failing due to additional validation in ZIP64 
(https://www.oracle.com/java/technologies/javase/11-0-20-relnotes.html) java.util.zip.ZipFile has been updated to provide additional validation of ZIP64 extra fields when opening a ZIP file. This validation may be disabled by setting the system property jdk.util.zip.disableZip64ExtraFieldValidation to true.) 

more info :
https://help.liferay.com/hc/en-us/articles/17904500197389-java-util-zip-ZipException-Invalid-CEN-header-invalid-zip64-extra-data-field-size-when-starting-dxp-using-JDK-11-0-20.

#### How to reproduce

Describe the bug and list the steps you used when the issue occurred.

#### Screenshots

![image](https://github.com/eclipse-sw360/sw360/assets/6360640/941f0d99-a0fe-44c3-b9ac-21b5eff8d1da)

### Versions

* Last commit id on master:
* Operating System (lsb_release -a):

### Logs

Any logs (if any) generated in

#### SW360 logs

Logs generated under /var/log/sw360/sw360.log

#### Tomcat logs

Logs generated under /var/log/tomcat/error.log

**Comment by dineshr93** [comment]
Hi @ag4ums  

since I run baremetal upgrade of sw360 from 17.0.0 to 18.1.0-M2 I encountered same error with java 
I tried 

```
export JAVA_OPTS="$JAVA_OPTS -Djdk.util.zip.disableZip64ExtraFieldValidation=true"
export MAVEN_OPTS="$MAVEN_OPTS -Djdk.util.zip.disableZip64ExtraFieldValidation=true"
```

`mvn clean install -DskipTests`  didnt work.

So, I added below line to `sw360/pom.xml` 


```
<systemPropertyVariables>
    <jdk.util.zip.disableZip64ExtraFieldValidation>true</jdk.util.zip.disableZip64ExtraFieldValidation>
</systemPropertyVariables>
```
below this line
 https://github.com/eclipse-sw360/sw360/blob/e9ca9498921fbc871f91ba9ec600ea1e6fc205c6/pom.xml#L667

even then `mvn clean install -DskipTests` did not work. 

I get 

![image](https://github.com/user-attachments/assets/231e2860-93ac-4491-a9d2-cdbd913199e6)

Please is there any way to resolve this ?
I am using `openjdk 11.0.22 2024-01-16`

**Comment by dineshr93** [comment]
Hi @ag4ums  okay ignore this I was applying` sudo mvn` instead of `mvn` . it is not picking up the java env variables when sudoing
