### ISSUE TITLE
The moderation request of user (Request Roles: User) is not displayed.

### ISSUE THREAD

**Issue by BinhTH-tsdv** [eclipse-sw360/sw360#652]
I have 4 users: User1, User2, User3, User4.
User1: Requested Role = Admin (Assign Site Roles: Site Owner)
User2,3,4: Requested Roles = User (Assign Site Roles: Site Content Reviewer)
User1 creat a component with assigned moderators( Moderators list include User1,2,3).
But User2,3 don't received any moderation request from the creating component.
Is this Bug or sw360's feature?

**Comment by mcjaeger** [comment]
it is a bug.

**Comment by mcjaeger** [comment]
Ha, rereading again, it seems like the user have been created with liferay. Please note that you must create the users by using the import functionality (otherwise the users are not created with the appropriate roles). Please refer to the section `Import Users` at the end of this documentation:

https://github.com/eclipse/sw360/wiki/Deploy-Liferay7

@BinhTH-tsdv  Does this maybe match your issue?

**Comment by mcjaeger** [comment]
I have the impression that the moderation request sending / assigning is not anmore as it was originally intended ... therefore I propose to retest the issue
